name: pycmt_env
channels:
  - conda-forge
dependencies:
  # Core language and notebook integration
  - python=3.11
  - jupyter
  - ipykernel
  
  # Geospatial & Data stack (conda-forge handles the heavy external binaries)
  - xcast
  - xarray
  - netcdf4
  - matplotlib
  - cartopy
  - cfgrib
  
  # Pip section to install your package cleanly
  - pip
  - pip:
    - git+https://github.com/elmamounedieye/pycmt.git