[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycmt"
version = "0.1.0"
description = "Python Climate Monitoring Tools"
authors = [
    {name = "Mouhamed El Mamoune Dieye"}
]

[project.scripts]
pycmt = "pycmt.climonitor:main"

dependencies = [
    "affine",
    "Cartopy",
    "cdo",
    "cftime",
    "dask",
    "geopandas",
    "Jinja2",
    "matplotlib",
    "netCDF4",
    "numba",
    "numpy",
    "openpyxl",
    "pandas",
    "pyogrio",
    "pyproj",
    "pyshp",
    "PyYAML",
    "rasterio",
    "requests",
    "rioxarray",
    "scipy",
    "shapely",
    "xarray",
    "xgrads"
]

[tool.setuptools]
# AUTOMATION : Force la recherche récursive de TOUS tes sous-dossiers (core, modules, visualization)
packages = { find = { where = ["src"] } }
include-package-data = true

[tool.setuptools.package-data]
# Sécurité pour inclure le dossier data interne
"pycmt" = ["data/**/*", "data/*"]